# Generated by Django 4.1.3 on 2022-11-12 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviegenre',
            name='genre_name',
            field=models.TextField(db_index=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='moviedetails',
            constraint=models.UniqueConstraint(fields=('movie_name', 'director'), name='unique_migration_host_combination'),
        ),
    ]
